sudo: required
service:
  - docker

before_install:
  - docker build -t balkanbgboy/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true balkanbgboy/react-test npm test

after_success:
  - docker build -t balkanbgboy/multi-client ./client
  - docker build -t balkanbgboy/multi-nginx ./nginx
  - docker build -t balkanbgboy/multi-server ./server
  - docker build -t balkanbgboy/multi-worker ./worker
  # Log in to Docker CLI
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin docker.io
  # Take those images and push them to docker Hub
  - docker push balkanbgboy/multi-client
  - docker push balkanbgboy/multi-nginx
  - docker push balkanbgboy/multi-server
  - docker push balkanbgboy/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: fib-calculator
  env: FibCalculator-env
  bucket_name: elasticbeanstalk-eu-central-1-310717640608
  bucket_path: fib-calculator
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY